<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Getting Started with Cromwell | WDL 101: Running WDLs using Cromwell</title>
  <meta name="description" content="An introduction to using the workflow manager software Cromwell to run WDL workflows on the Fred Hutch computing cluster." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Getting Started with Cromwell | WDL 101: Running WDLs using Cromwell" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="An introduction to using the workflow manager software Cromwell to run WDL workflows on the Fred Hutch computing cluster." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Getting Started with Cromwell | WDL 101: Running WDLs using Cromwell" />
  
  <meta name="twitter:description" content="An introduction to using the workflow manager software Cromwell to run WDL workflows on the Fred Hutch computing cluster." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
<link rel="prev" href="introduction.html"/>
<link rel="next" href="using-cromwell-at-fred-hutch.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="assets/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<a href="https://hutchdatascience.org/" target="_blank"><img src="assets/big-dasl-stacked.png" style="width: 80%; padding-left: 34px; padding-top: 8px;"</a>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About this Guide</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#what-is-wdl"><i class="fa fa-check"></i><b>1.1</b> What is WDL?</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#what-is-cromwell"><i class="fa fa-check"></i><b>1.2</b> What is Cromwell?</a></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#using-cromwell"><i class="fa fa-check"></i><b>1.3</b> Using Cromwell</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-started-with-cromwell.html"><a href="getting-started-with-cromwell.html"><i class="fa fa-check"></i><b>2</b> Getting Started with Cromwell</a>
<ul>
<li class="chapter" data-level="2.1" data-path="getting-started-with-cromwell.html"><a href="getting-started-with-cromwell.html#prerequisites"><i class="fa fa-check"></i><b>2.1</b> Prerequisites</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="getting-started-with-cromwell.html"><a href="getting-started-with-cromwell.html#rhino-access"><i class="fa fa-check"></i><b>2.1.1</b> <code>rhino</code> Access</a></li>
<li class="chapter" data-level="2.1.2" data-path="getting-started-with-cromwell.html"><a href="getting-started-with-cromwell.html#optional-aws-credentials"><i class="fa fa-check"></i><b>2.1.2</b> (Optional) AWS Credentials</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="getting-started-with-cromwell.html"><a href="getting-started-with-cromwell.html#database-setup"><i class="fa fa-check"></i><b>2.2</b> Database Setup</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="getting-started-with-cromwell.html"><a href="getting-started-with-cromwell.html#get-your-database-container"><i class="fa fa-check"></i><b>2.2.1</b> Get Your Database Container</a></li>
<li class="chapter" data-level="2.2.2" data-path="getting-started-with-cromwell.html"><a href="getting-started-with-cromwell.html#make-your-empty-database"><i class="fa fa-check"></i><b>2.2.2</b> Make Your Empty Database</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="getting-started-with-cromwell.html"><a href="getting-started-with-cromwell.html#start-up-your-first-cromwell-server"><i class="fa fa-check"></i><b>2.3</b> Start up your first Cromwell server</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="getting-started-with-cromwell.html"><a href="getting-started-with-cromwell.html#customize-your-configuration"><i class="fa fa-check"></i><b>2.3.1</b> Customize Your Configuration</a></li>
<li class="chapter" data-level="2.3.2" data-path="getting-started-with-cromwell.html"><a href="getting-started-with-cromwell.html#kick-off-your-cromwell-server"><i class="fa fa-check"></i><b>2.3.2</b> Kick off your Cromwell server</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="getting-started-with-cromwell.html"><a href="getting-started-with-cromwell.html#starting-up-your-server-in-the-future"><i class="fa fa-check"></i><b>2.4</b> Starting up your server in the future</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="using-cromwell-at-fred-hutch.html"><a href="using-cromwell-at-fred-hutch.html"><i class="fa fa-check"></i><b>3</b> Using Cromwell at Fred Hutch</a>
<ul>
<li class="chapter" data-level="3.1" data-path="using-cromwell-at-fred-hutch.html"><a href="using-cromwell-at-fred-hutch.html#everyday-usage"><i class="fa fa-check"></i><b>3.1</b> Everyday Usage</a></li>
<li class="chapter" data-level="3.2" data-path="using-cromwell-at-fred-hutch.html"><a href="using-cromwell-at-fred-hutch.html#test-workflows"><i class="fa fa-check"></i><b>3.2</b> Test Workflows</a></li>
<li class="chapter" data-level="3.3" data-path="using-cromwell-at-fred-hutch.html"><a href="using-cromwell-at-fred-hutch.html#runtime-variables"><i class="fa fa-check"></i><b>3.3</b> Runtime Variables</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="using-cromwell-at-fred-hutch.html"><a href="using-cromwell-at-fred-hutch.html#standard-runtime-variables"><i class="fa fa-check"></i><b>3.3.1</b> Standard Runtime Variables</a></li>
<li class="chapter" data-level="3.3.2" data-path="using-cromwell-at-fred-hutch.html"><a href="using-cromwell-at-fred-hutch.html#fred-hutch-custom-runtime-variables"><i class="fa fa-check"></i><b>3.3.2</b> Fred Hutch Custom Runtime Variables</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="using-cromwell-at-fred-hutch.html"><a href="using-cromwell-at-fred-hutch.html#managing-software-environments"><i class="fa fa-check"></i><b>3.4</b> Managing Software Environments</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="using-cromwell-at-fred-hutch.html"><a href="using-cromwell-at-fred-hutch.html#modules"><i class="fa fa-check"></i><b>3.4.1</b> Modules</a></li>
<li class="chapter" data-level="3.4.2" data-path="using-cromwell-at-fred-hutch.html"><a href="using-cromwell-at-fred-hutch.html#docker"><i class="fa fa-check"></i><b>3.4.2</b> Docker</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="using-shiny-to-manage-workflows.html"><a href="using-shiny-to-manage-workflows.html"><i class="fa fa-check"></i><b>4</b> Using Shiny to Manage Workflows</a>
<ul>
<li class="chapter" data-level="4.1" data-path="using-shiny-to-manage-workflows.html"><a href="using-shiny-to-manage-workflows.html#get-test-workflows"><i class="fa fa-check"></i><b>4.1</b> Get Test Workflows</a></li>
<li class="chapter" data-level="4.2" data-path="using-shiny-to-manage-workflows.html"><a href="using-shiny-to-manage-workflows.html#login"><i class="fa fa-check"></i><b>4.2</b> Login</a></li>
<li class="chapter" data-level="4.3" data-path="using-shiny-to-manage-workflows.html"><a href="using-shiny-to-manage-workflows.html#submit-jobs-tab"><i class="fa fa-check"></i><b>4.3</b> Submit Jobs Tab</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="using-shiny-to-manage-workflows.html"><a href="using-shiny-to-manage-workflows.html#validate-a-workflow"><i class="fa fa-check"></i><b>4.3.1</b> Validate a workflow</a></li>
<li class="chapter" data-level="4.3.2" data-path="using-shiny-to-manage-workflows.html"><a href="using-shiny-to-manage-workflows.html#submit-a-workflow"><i class="fa fa-check"></i><b>4.3.2</b> Submit a workflow</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="using-shiny-to-manage-workflows.html"><a href="using-shiny-to-manage-workflows.html#track-jobs-tab"><i class="fa fa-check"></i><b>4.4</b> Track Jobs Tab</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="using-shiny-to-manage-workflows.html"><a href="using-shiny-to-manage-workflows.html#history-of-workflows"><i class="fa fa-check"></i><b>4.4.1</b> History of workflows</a></li>
<li class="chapter" data-level="4.4.2" data-path="using-shiny-to-manage-workflows.html"><a href="using-shiny-to-manage-workflows.html#diving-into-a-workflow"><i class="fa fa-check"></i><b>4.4.2</b> Diving into a Workflow</a></li>
<li class="chapter" data-level="4.4.3" data-path="using-shiny-to-manage-workflows.html"><a href="using-shiny-to-manage-workflows.html#call-level-information"><i class="fa fa-check"></i><b>4.4.3</b> Call Level Information</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="using-shiny-to-manage-workflows.html"><a href="using-shiny-to-manage-workflows.html#troubleshoot-tab"><i class="fa fa-check"></i><b>4.5</b> Troubleshoot Tab</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="using-shiny-to-manage-workflows.html"><a href="using-shiny-to-manage-workflows.html#abort-a-workflow"><i class="fa fa-check"></i><b>4.5.1</b> Abort a workflow</a></li>
<li class="chapter" data-level="4.5.2" data-path="using-shiny-to-manage-workflows.html"><a href="using-shiny-to-manage-workflows.html#troubleshoot-a-workflow"><i class="fa fa-check"></i><b>4.5.2</b> Troubleshoot a workflow</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="using-shiny-to-manage-workflows.html"><a href="using-shiny-to-manage-workflows.html#run-test-workflows"><i class="fa fa-check"></i><b>4.6</b> Run Test Workflows</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="using-the-fh.wdlr-package.html"><a href="using-the-fh.wdlr-package.html"><i class="fa fa-check"></i><b>5</b> Using the <code>fh.wdlR</code> Package</a>
<ul>
<li class="chapter" data-level="5.1" data-path="using-the-fh.wdlr-package.html"><a href="using-the-fh.wdlr-package.html#install-fh.wdlr-from-github"><i class="fa fa-check"></i><b>5.1</b> Install <code>fh.wdlR</code> from GitHub</a></li>
<li class="chapter" data-level="5.2" data-path="using-the-fh.wdlr-package.html"><a href="using-the-fh.wdlr-package.html#example-workflow-process"><i class="fa fa-check"></i><b>5.2</b> Example workflow process</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="using-the-fh.wdlr-package.html"><a href="using-the-fh.wdlr-package.html#validate-your-workflow-formatting"><i class="fa fa-check"></i><b>5.2.1</b> Validate your workflow formatting</a></li>
<li class="chapter" data-level="5.2.2" data-path="using-the-fh.wdlr-package.html"><a href="using-the-fh.wdlr-package.html#submit-workflows"><i class="fa fa-check"></i><b>5.2.2</b> Submit Workflows</a></li>
<li class="chapter" data-level="5.2.3" data-path="using-the-fh.wdlr-package.html"><a href="using-the-fh.wdlr-package.html#track-workflows"><i class="fa fa-check"></i><b>5.2.3</b> Track Workflows</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="using-the-fh.wdlr-package.html"><a href="using-the-fh.wdlr-package.html#look-under-the-hood"><i class="fa fa-check"></i><b>5.3</b> Look Under the Hood</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="summary-and-next-steps.html"><a href="summary-and-next-steps.html"><i class="fa fa-check"></i><b>6</b> Summary and Next Steps</a>
<ul>
<li class="chapter" data-level="6.1" data-path="summary-and-next-steps.html"><a href="summary-and-next-steps.html#fred-hutch-wdl-102"><i class="fa fa-check"></i><b>6.1</b> Fred Hutch WDL 102</a></li>
<li class="chapter" data-level="6.2" data-path="summary-and-next-steps.html"><a href="summary-and-next-steps.html#documentation-in-the-wild"><i class="fa fa-check"></i><b>6.2</b> Documentation in the Wild</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="summary-and-next-steps.html"><a href="summary-and-next-steps.html#openwdl-specification"><i class="fa fa-check"></i><b>6.2.1</b> openWDL specification</a></li>
<li class="chapter" data-level="6.2.2" data-path="summary-and-next-steps.html"><a href="summary-and-next-steps.html#openwdl-documentation"><i class="fa fa-check"></i><b>6.2.2</b> openWDL Documentation</a></li>
<li class="chapter" data-level="6.2.3" data-path="summary-and-next-steps.html"><a href="summary-and-next-steps.html#cromwell-documentation"><i class="fa fa-check"></i><b>6.2.3</b> Cromwell Documentation</a></li>
<li class="chapter" data-level="6.2.4" data-path="summary-and-next-steps.html"><a href="summary-and-next-steps.html#workflow-content"><i class="fa fa-check"></i><b>6.2.4</b> Workflow Content</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="summary-and-next-steps.html"><a href="summary-and-next-steps.html#fred-hutch-guidance-and-support"><i class="fa fa-check"></i><b>6.3</b> Fred Hutch Guidance and Support</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="summary-and-next-steps.html"><a href="summary-and-next-steps.html#effective-computing-drop-in-hour"><i class="fa fa-check"></i><b>6.3.1</b> Effective Computing Drop In Hour</a></li>
<li class="chapter" data-level="6.3.2" data-path="summary-and-next-steps.html"><a href="summary-and-next-steps.html#slack-workflow-manager-channel"><i class="fa fa-check"></i><b>6.3.2</b> Slack Workflow Manager Channel</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html"><i class="fa fa-check"></i>About the Authors</a></li>
<li class="divider"></li>
<p style="text-align:center;"> <a href="https://github.com/jhudsl/OTTR_Template" target="blank" > This content was published with</a> <a href="https://bookdown.org/" target="blank"> bookdown by: </a> </p>
<p style="text-align:center;"> <a href="https://hutchdatascience.org/"> The Fred Hutch Data Science Lab </a></p>
<p style="text-align:center; font-size: 12px;"> <a href="https://github.com/rstudio4edu/rstudio4edu-book/"> Style adapted from: rstudio4edu-book </a> <a href ="https://creativecommons.org/licenses/by/2.0/"> (CC-BY 2.0) </a></p>
<p style="padding-left: 40px;"><div class="trapezoid" style = "padding-left: 40px;"><span>  <a href="https://forms.gle/W6Mg4rzuMK6Yk3Am8"> Click here to provide feedback</a> <img src="assets/itcr_arrow.png" style=" width: 10%" ></span></div></p>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">WDL 101: Running WDLs using Cromwell</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<head>
  <meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=10.0,initial-scale=1.0">
  <!--script src="https://kit.fontawesome.com/6a26f47516.js"></script-->
  <!--<script src="assets/hideOutput.js"></script>-->
  <link href="assets/style.css" rel="stylesheet">
</head>
        


<div class="hero-image-container"> 
  <img class= "hero-image" src="assets/dasl_thin_main_image.png">
</div>
<div id="getting-started-with-cromwell" class="section level1" number="2">
<h1><span class="header-section-number">Chapter 2</span> Getting Started with Cromwell</h1>
<p>To get set up using Cromwell at the Fred Hutch, there is a setup process you need to do only one time in order to customize how Cromwell runs for you. This guide aims to help you get these two steps set up correctly so that in the future you can just run Cromwell directly.</p>
<div id="prerequisites" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> Prerequisites</h2>
<div id="rhino-access" class="section level3" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> <code>rhino</code> Access</h3>
<p>Either you need to have gotten access to use the Fred Hutch SLURM cluster prior OR have taken our “Cluster 101” course. You can find this <strong>free</strong> course <a href="https://leanpub.com/courses/fredhutch/fredhutchcluster101">here</a>.
To follow this course, you’ll need to know how to get onto the <code>rhino</code> nodes. If this is not something you are familiar with, you also may want to read a bit more about the use of our cluster over at <a href="https://sciwiki.fredhutch.org/">SciWiki</a> in the Scientific Computing section about Access Methods, and Technologies.</p>
</div>
<div id="optional-aws-credentials" class="section level3" number="2.1.2">
<h3><span class="header-section-number">2.1.2</span> (Optional) AWS Credentials</h3>
<p>If you want to run workflows on data stored in AWS S3, you’ll need to have <a href="https://sciwiki.fredhutch.org/scicomputing/access_credentials/#amazon-web-services-aws">set up your AWS credentials</a> first.<br />
As of version 1.3 of the diy-cromwell-server configuration, if you have credentials, then the Cromwell server will be configured to allow input files to be directly specified using their AWS S3 url.<br />
However if you do not have AWS credentials or aren’t using data stored in AWS S3, then you don’t have to do anything.</p>
</div>
</div>
<div id="database-setup" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Database Setup</h2>
<p>One of the strengths of using Cromwell is that it can allow you to keep track of what you’ve already done so you don’t have to re-compute jobs that have already completed successfully even if some of your workflow fails. To leverage this feature, called “call caching” and also use our computing resources efficiently, our configuration of Cromwell will help you set up a Cromwell server for 7 days at a time and creates a database that persists forever that the Cromwell servers can communicate with. We have found that by using a MySQL database for your Cromwell server to store information in, it will run faster and be better able to handle simultaneous workflows while also making all the metadata available to you during and after the run.</p>
<div id="get-your-database-container" class="section level3" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Get Your Database Container</h3>
<p>Thus for each user, we suggest setting up a database using the following steps. This only needs to be done one time per user.</p>
<ol style="list-style-type: decimal">
<li>Go to <a href="https://mydb.fredhutch.org/login">DB4Sci</a> and see the Wiki entry for DB4Sci <a href="https://sciwiki.fredhutch.org/scicomputing/store_databases/#db4sci--previously-mydb">here</a>.<br />
</li>
<li>Login using your Fred Hutch credentials
<img src="assets/cromwell/db4sciLogin.png" title="DB4Sci Login" alt="db4scilong" style="display: block; margin: auto;" /></li>
<li>Choose <code>Create DB Container</code>, and choose the MariaDB (MySQL) option.<br />
<img src="assets/cromwell/db4sci.png" title="DB4Sci interface" alt="db4sci" style="display: block; margin: auto;" /></li>
<li>Use the following:
<ul>
<li>Your DB Username can be whatever you want</li>
<li>Your DB Password should not be your Fred Hutch password</li>
<li>Provide a Contact name and your fredhutch.org email</li>
<li>Provide a Description (like “Cromwell database”)</li>
<li>Set <code>Expected Life of DB</code>: Choose “Long (36+ mo)”</li>
<li>Set <code>Frequency of Backup</code>: “Never”
<img src="assets/cromwell/mariadb.png" title="DB4Sci interface" alt="db4sci" style="display: block; margin: auto;" /></li>
</ul></li>
<li>Save the <code>DB/Container Name</code>, <code>DB Username</code> and <code>DB Password</code> somewhere handy as you will need them for the configuration step.<br />
</li>
<li>Click submit, a confirmation screen will appear (hopefully), and you’ll need to note which <code>Port</code> is specified. This is a 5 digit number currently. Write this down!!! If you have trouble with using DB4Sci, you can email <code>scicomp@fredhutch.org</code> and share the information or screen shots of what failed to get help.</li>
</ol>
<blockquote>
<p>Note: If you do not see this screen, you can go to the <code>Manage Containers</code> tab in the MyDB interface and scroll down for your container name, and you can look in the <code>Port</code> column.</p>
</blockquote>
<p>At this point you should have a sticky note or something handy where you’ve put the DB Name, DB Username, DB Password and Port ready for the next steps.</p>
</div>
<div id="make-your-empty-database" class="section level3" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> Make Your Empty Database</h3>
<p>Now you have a “container” in which to run a database, but the database itself does not yet exist. Again, this only needs to be done one time per user.
You need to create an empty database in that container and then Cromwell will do the rest the first time you start up a server.</p>
<p>To create the database, you’ll need to go to Terminal and connect to <code>rhino</code> then enter the following (where you replace the entire <code>&lt;Port&gt;</code> including the &lt; and &gt; with the text, for example, <code>34567</code>).</p>
<pre><code>ml MariaDB/10.5.1-foss-2019b
mysql --host mydb --port &lt;Port&gt; --user &lt;username&gt; --password</code></pre>
<p>It will then prompt you to enter the DB password you specified during setup. Once you are are a “mysql&gt;” prompt, you can do the following.</p>
<blockquote>
<p>Note, we suggest you name the database inside the container the same as the container, but you cannot include dashes in your database name.</p>
</blockquote>
<pre><code>MariaDB [(none)]&gt; create database &lt;DB Name&gt;;
## It should do its magic - if it works it says:
#Query OK, 1 row affected
MariaDB [(none)]&gt; exit
#Bye</code></pre>
<p>Now you’re ready to go and never have to set up the database part again and you can use this database to manage all your work over time!</p>
</div>
</div>
<div id="start-up-your-first-cromwell-server" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Start up your first Cromwell server</h2>
<p>Now that you’ve set up your database so it’s ready for Cromwell to talk to it and save your workflow information to it, you will customize Cromwell to work how you want it to work and you’ll be ready to use it!</p>
<div id="customize-your-configuration" class="section level3" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> Customize Your Configuration</h3>
<p>To start up your first Cromwell server job, you first need to decide where you want to keep your Cromwell configuration files. This must be a place where <code>rhino</code> can access them, such as in your <code>Home</code> directory, which is typically the default directory when you connect to the <code>rhinos</code>. We suggest you create a <code>cromwell-home</code> folder (or whatever you want to call it) and follow these git instructions to clone it directly.</p>
<p>Then you will set up the customizations that you’re going to want for your server(s) by making user configuration file(s) in your <code>cromwell-home</code> or wherever you find convenient.</p>
<p>You can manage multiple Cromwell profiles this way by just maintaining different files full of credentials and configuration variables that you want.</p>
<p>To get started, do the following on <code>rhino</code>:</p>
<pre><code>mkdir -p cromwell-home
cd cromwell-home
git clone --branch main https://github.com/FredHutch/diy-cromwell-server.git</code></pre>
<p>Next you’ll want to move the cromUserConfig.txt template file you just downloaded into your main <code>cromwell-home</code> directory for customization and keeping in the future.</p>
<pre><code>cp ./diy-cromwell-server/cromUserConfig.txt .
## When you are first setting up Cromwell, you&#39;ll need to put all of your User Customizations into this `cromUserConfig.txt` which can serve as a template.  
## After you&#39;ve done this once, you just need to keep the path to the file(s) handy for the future.  </code></pre>
<p>In <code>cromUserConfig.txt</code> there are some variables that allow users to share a similar configuration file but tailor the particular behavior of their Cromwell server to best suit them.<br />
The following text is also in this repo but these are the customizations you’ll need to decide on for your server.</p>
<pre><code>################## WORKING DIRECTORY AND PATH CUSTOMIZATIONS ###################
## Where do you want the working directory to be for Cromwell
## Note: startng the server will create a subdirectory in the directory you specify here called &quot;cromwell-executions&quot;). Please include the leading and trailing slashes!!! You likely will want to include your username in the path just in case others in your lab are ALSO using Cromwell to reduce confusion.
### Suggestion: /fh/scratch/delete90/pilastname_f/username/
SCRATCHDIR=/fh/scratch/delete90/...

## Where do you want logs about individual workflows (not jobs) to be written?
## Note: this is a default for the server and can be overwritten for a given workflow in workflow-options.  Most of the time workflow troubleshooting occurs without having to refer to these logs, but the ability to make them can be useful if you like them. 
### Suggestion: ~/cromwell-home/workflow-logs
WORKFLOWLOGDIR=~/cromwell-home/workflow-logs

## Where do you want to save Cromwell server logs for troubleshooting Cromwell itself?
## You&#39;ll want this handy in the beginning as when Cromwell cannot start up, this is where you&#39;ll go to do all of your troubleshooting.  
### Suggestion: ~/cromwell-home/server-logs
SERVERLOGDIR=~/cromwell-home/server-logs

################ DATABASE CUSTOMIZATIONS #################
## DB4Sci MariaDB details (remove any `...`&#39;s and use unquoted text):

CROMWELLDBPORT=...
CROMWELLDBNAME=...
CROMWELLDBUSERNAME=...
CROMWELLDBPASSWORD=...

## Number of cores for your Cromwell server itself - usually 4 is sufficient.  
## Increase if you want to run many, complex workflows simultaneously or notice your server is slowing down. Keep in mind these cpu&#39;s do count toward your lab&#39;s allocations, so you want to keep it fairly minimal. 
NCORES=4

## Length of time you want the server to run for.  
## Note: when servers go down, all jobs they&#39;d sent will continue.  When you start up a server the next time using the same database, the new server will pick up whereever the previous workflows left off.  &quot;7-0&quot; is 7 days, zero hours.
SERVERTIME=&quot;7-0&quot; </code></pre>
<blockquote>
<p>Note: For this server, you will want multiple cores to allow it to multi-task. If you notice issues, the particular resource request for the server job itself might be a good place to start adjusting, in conjunction with some guidance from SciComp or the Slack <a href="https://fhbig.slack.com/archives/CD3HGJHJT">Question and Answer channel</a> folks.</p>
</blockquote>
</div>
<div id="kick-off-your-cromwell-server" class="section level3" number="2.3.2">
<h3><span class="header-section-number">2.3.2</span> Kick off your Cromwell server</h3>
<p>Now that you’ve configured your future Cromwell servers, you can kick off your first Cromwell server job. Go to <code>rhino</code> to your “cromwell-home” and do the following:</p>
<pre><code>## You&#39;ll want to put `cromwell.sh` somewhere handy for future use, we suggest:
cp ./diy-cromwell-server/cromwell.sh .

## Then you&#39;ll want to make the script &quot;executable&quot;:
chmod +x cromwell.sh

# Then simply start up Cromwell by executing the script and passing it the path to your configuration file. 
./cromwell.sh cromUserConfig.txt</code></pre>
<p>Much like the <code>grabnode</code> command you may have used previously, the script will run and print back to the console instructions once the resources have been provisioned for the server. You should see something like this:</p>
<pre><code>Your configuration details have been found...
Getting an updated copy of Cromwell configs from GitHub...
Setting up all required directories...
Detecting existence of AWS credentials...
Credentials found, setting appropriate configuration...
Requesting resources from SLURM for your server...
Submitted batch job 2733799
Your Cromwell server is attempting to start up on node/port gizmob5:39071.  It can take up to 2 minutes prior to the port being open for use by the shiny app at https://cromwellapp.fredhutch.org or via the R package fh.wdlR. If you encounter errors, you may want to check your server logs at /home/username/cromwell-home/server-logs to see if Cromwell was unable to start up.
Go have fun now.</code></pre>
<blockquote>
<p>IMPORTANT NOTE: Please write down the node and port it specifies here - in this example it’s <code>gizmob5:39071</code>, but yours will be a different combination. This is the only place where you will be able to find the particular node/port for this instance of your Cromwell server, and you’ll need that to be able to send jobs to the Cromwell server. If you forget it, <code>scancel</code> the Cromwell server job and start a new one.</p>
</blockquote>
<p>While your server will normally stop after 7 days (the default), at which point if you have jobs still running you can simply restart your server and it will reconnect to existing jobs/workflows. However, if you need to take down your server for whatever reason before that point, you can go to <code>rhino</code> and do:</p>
<pre><code>## Here `username` is your Fred Hutch username
squeue -u username
## Or if you want to get fancy:
squeue -o &#39;%.18i %.9P %j %.8T %.10M %.9l %.6C %R&#39; -u username</code></pre>
<p>You’ll see a jobname “cromwellServer”. Next to that will be a JOBID. In this example the JOBID of the server is 2733799.</p>
<p><img src="assets/cromwell/squeue.png" title="Your Cromwell server running on Gizmo" alt="squeue results" style="display: block; margin: auto;" /></p>
<p>If you ever want to shut down your server before the 7 day default run time, you can always go to Rhino in your Terminal and end the server by doing:</p>
<pre><code>scancel 2733799
</code></pre>
</div>
</div>
<div id="starting-up-your-server-in-the-future" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> Starting up your server in the future</h2>
<p>Good news! The above instructions are a one time event. In the future, when you want to start up a Cromwell server to do some computing work, all you’ll have to do is:</p>
<ol style="list-style-type: decimal">
<li><p>Get onto Rhino in Terminal</p></li>
<li><p>Change to the <code>cromwell-home</code> directory you made</p></li>
<li><p>Enter: <code>./cromwell.sh cromUserConfig.txt</code> and you’re off to the races!</p></li>
</ol>
<p>Congrats you’ve started your first Cromwell server!!</p>

</div>
</div>
<hr>
<center> 
  <div class="footer">
      All illustrations <a href="https://creativecommons.org/licenses/by/4.0/">CC-BY. </a>
      <br>
      All other materials <a href= "https://creativecommons.org/licenses/by/4.0/"> CC-BY </a> unless noted otherwise.
  </div>
</center>
            </section>

          </div>
        </div>
      </div>
<a href="introduction.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="using-cromwell-at-fred-hutch.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
