
```{r, include = FALSE}
ottrpal::set_knitr_image_path()
```
# Testing Cromwell and the Fred Hutch Custom Configuration

## Test Workflows

See our [Test Workflow folder](https://github.com/FredHutch/diy-cromwell-server/tree/main/testWorkflows) once your server is up and run through the tests specified in the markdown there. 
> NOTE: For those test workflows that use Docker containers, know that the first time you run them, you may notice that jobs aren't being sent very quickly.  That is because for our cluster, we need to convert those Docker containers to something that can be run by Singularity.  The first time a Docker container is used, it must be converted, but in the future Cromwell will used the cached version of the Docker container and jobs will be submitted more quickly. 

You can see what is currently available in the FredHutch GitHub institution by using [this link to search results](https://github.com/FredHutch?utf8=%E2%9C%93&q=wdl+OR+cromwell&type=&language=).



## Fred Hutch Runtime Customizations


### Task Defaults and Runtime Variables
For the gizmo backend, the following runtime variables are available that are customized to our configuration.  What is specified below is the current default as written, you can edit these in the config file if you'd like OR you can specify these variables in your `runtime` block in each task to change only the variables you want to change from the default for that particular task.  

- `cpu = 1`
  - An integer number of cpus you want for the task
- `walltime = "18:00:00"`
  - A string of date/time that specifies how many hours/days you want to request for the task
- `memory = 2000`
  - An integer number of MB of memory you want to use for the task
- `partition = "campus-new"`
  - Which partition you want to use, the default is `campus-new` but whatever is in the runtime block of your WDL will overrride this. 
- `modules = ""`
  - A space-separated list of the environment modules you'd like to have loaded (in that order) prior to running the task.  
- `docker = "ubuntu:latest"`
  - A specific Docker container to use for the task.  For the custom Hutch configuration, docker containers can be specified and the necessary conversions (to Singularity) will be performed by Cromwell (not the user).  Note: when docker is used, soft links cannot be used in our filesystem, so workflows using very large datasets may run slightly slower due to the need for Cromwell to copy files rather than link to them.  
- `dockerSL= "ubuntu:latest"`
  - This is a custom configuration for the Hutch that allows users to use docker and softlinks only to specific locations in Scratch.  It is helpful when working with very large files. 


## Guidance and Support
### Effective Computing User Group
This is a drop-in style biweekly meeting that provides resources for folks to talk about their computational work and improve over time.  Find current events by checking out the FH-Data Slack workspace [here](https://fhdata.slack.com).



## Running Workflows


### Workflow options


### Modules vs Docker
- cloud will require docker but working locally does not
- docker requires copying of inputs (does not allow for softlinks) so when using big data inputs this can be slower than using modules/softlinks

### Managing Results
Best practices include:
- using Scratch for all work in progress
- copy only required, final, archivable workflow outputs to Fast or AWS S3 using workflow options
- copy WDL, and any input json or workflow options files to same directory as archived results for a "complete" data package
- commit code to GitHub and consider versioning/creating a release to more thoroughly document and share code associated with the above data package. 