# Basic WDL Development

## Workflow Structure


### Inputs


### Tasks


#### Inputs

#### Command

#### Outputs

#### Runtime


### Managing Software Environments


## Wiring Tasks Together



## Developing a new Workflow

### Start from a template
Preferably one that executes cleanly - even if it's Hello World.

### Chose Software Modules
Test interactively with software modules on the cluster to see what inputs are required, what parameters you want to specify, what outputs get created. 

### Add Tasks
Define tasks, using modules, test data (truncated files, scatters of 1), run and test.


### Scale Up Inputs
Start to run workflow on full size data (scatters of 1), then start to scatter over several files, then scatter over entire datasets. 


### Prep for Other Platforms and Sharing
Shift to docker containers instead of modules, ensure that all inputs are specified as files not directories!!, start to optmize compute resources required for tasks (how much memory does it really need, or is it going to need many CPU's).






